export const ACTION_ID_ADD_SOTD = "ACTION_ID_ADD_SOTD";
export const ACTION_ID_GET_SOTD = "ACTION_ID_GET_SOTD";
export const ACTION_ID_SUBMIT_SOTD = "ACTION_ID_SUBMIT_SOTD";
export const MS_PER_DAY = 60000 * 60 * 24;
